query GetLibraryTestCases($ids: [String]!) {
  libraryTestcasesByIds(ids: $ids) {
    nodes {
      id
      name
      description
      method
      libraryTestCaseId
      mitreId
      attackSuccess
      organizations {
        name
      }
      defensiveLayers {
        name
      }
      operatorGuidance
      redTools {
        id
        name
        vendor {
          name
        }
      }
      metadata {
        key
        value
      }
      tags {
        name
      }
      phase {
        name
      }
      automationCmd
      automationExecutor
      automationCleanup
      automationCleanupExecutor
      automationArgument {
        argumentKey
        argumentValue
        argumentType
      }
      detectionGuidance
      preventionGuidance
      references
      userContext
      importTime
      attachmentFiles {
        id
        filename
        fileSize
        mimeType
        thumbnailData
        metadata
        createdAt
        updatedAt
      }
      completeTime {
        id
        team
        fieldName
        type
        manualDescription
        createdByUser {
          id
          username
        }
        lastUpdatedByUser {
          id
          username
        }
        createTime
        updateTime
        toolOutcomeChange {
          defenseToolId
          outcomeId
        }
        designation
      }
      unstructuredLogs {
        id
        content
        filename
        createTime
        updateTime
      }
      timelineEvents {
        id
        team
        fieldName
        fieldAction
        type
        manualDescription
        createdByUser {
          id
          username
        }
        lastUpdatedByUser {
          id
          username
        }
        createTime
        updateTime
        toolOutcomeChange {
          defenseToolId
          outcomeId
        }
        designation
      }
    }
  }
}