name: Weekly Checks

on:
  schedule:
    - cron: '0 8 * * 1' # Every Monday at 8am UTC
  workflow_dispatch:

jobs:
  weekly-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: Run vulncheck
        run: make vulncheck
      - name: Check for updates
        run: make check-updates
